color: green
description: null
fieldLayouts:
  8ee90140-9c51-4f6c-97fb-707c911e4233:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-08-16T15:44:56+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 5f716d6c-292b-479b-9f9c-aa4321bb3fd3 # field.sectionHeader
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4f6f3182-9ed2-43cd-aabb-ced6bf36cf63
            userCondition: null
            warning: null
            width: 100
        name: tab.content
        uid: a131fe91-5bc4-4d96-9ccf-d9b977b36e1a
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-08-16T15:16:59+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 6bd88332-fd2c-4f42-823f-6c6b5a97194d # field.blockSettings
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cec7ad16-903e-4f2f-b697-c9643c1679d3
            userCondition: null
            warning: null
            width: 100
        name: tab.settings
        uid: 9245dc85-5a3a-462c-b608-410f61ecac77
        userCondition: null
handle: header
hasTitleField: false
icon: a
name: block.header
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
