columnSuffix: null
handle: distance
instructions: null
name: field.distance
searchable: false
settings:
  decimals: 0
  defaultValue: null
  max: null
  min: 0
  prefix: null
  previewCurrency: null
  previewFormat: decimal
  size: null
  step: null
  suffix: rem
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
