columnSuffix: null
handle: pageBuilder
instructions: null
name: field.pageBuilder
searchable: false
settings:
  createButtonLabel: field.pageBuilder.add
  defaultIndexViewMode: cards
  enableVersioning: false
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - 1806f3ce-8ef8-44c7-b3d1-625b62307100 # block.header
        -
          - group
          - Ogólne
    -
      __assoc__:
        -
          - uid
          - 9f138cfe-9e3e-4c38-9bd9-87633b112c11 # block.richText
        -
          - group
          - Ogólne
    -
      __assoc__:
        -
          - uid
          - 30a44582-37d6-4702-9535-3397861bec07 # block.blockSharedContent
        -
          - group
          - Ogólne
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: null
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: blocks
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
