columnSuffix: null
handle: seoRobots
instructions: null
name: field.seoRobots
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - all
        -
          - value
          - all
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - none
        -
          - value
          - none
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
