columnSuffix: null
handle: showDefaultTitleSection
instructions: null
name: field.showDefaultTitleSection
searchable: false
settings:
  default: true
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
