columnSuffix: null
handle: switchDisabled
instructions: null
name: field.switchDisabled
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
