dateModified: 1755354671
email:
  fromEmail: kontakt@pogorzelskiweb.pl
  fromName: craft-theme-v4
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    3daa580c-b96b-48de-a5a6-f3e0a4f4a8e8: craft-theme-v4 # craft-theme-v4
    cf71bf77-a719-49b4-b683-65b57024486c: craft-theme-v4 # craft-theme-v4
system:
  edition: solo
  live: true
  name: craft-theme-v4
  schemaVersion: 5.8.0.3
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
